<?php

return [
    'newsapi' => [
        "key" => env('AGGR_NEWS_API_KEY', 'test'),
        "endpoint" => "https://newsapi.org/v2",
    ],
    "guardian" => [
        "key" => env("GUARDIAN_NEWS_API", 'test'),
        "endpoint" => "https://content.guardianapis.com",
    ],
    "ny" => [
        "key" => env('AGGR_APP_KEY', 'test'),
        "endpoint" => "https://api.nytimes.com/svc/search/v2/articlesearch.json",
    ],
    'language' => [
            'ar',
            'de',
            'en',
            'es',
            'fr',
            'he',
            'it',
            'nl',
            'no',
            'pt',
            'ru',
            'sv',
            'ud',
            'zh'
    ],
    'categories' => [
        'business',
            'entertainment',
            'general',
            'health',
            'science',
            'sports',
            'technology'
    ],
    'country' => [
        'ae',
            'ar',
            'at',
            'au',
            'be',
            'bg',
            'br',
            'ca',
            'ch',
            'cn',
            'co',
            'cu',
            'cz',
            'de',
            'eg',
            'fr',
            'gb',
            'gr',
            'hk',
            'hu',
            'id',
            'ie',
            'il',
            'in',
            'it',
            'jp',
            'kr',
            'lt',
            'lv',
            'ma',
            'mx',
            'my',
            'ng',
            'nl',
            'no',
            'nz',
            'ph',
            'pl',
            'pt',
            'ro',
            'rs',
            'ru',
            'sa',
            'se',
            'si',
            'sk',
            'th',
            'tr',
            'tw',
            'ua',
            'us',
            've',
            'za'
    ]
];
